#!/usr/bin/python3
#
#
import datetime
import inspect
import sys
import time

import smaxsmt

# FIXME: is there a way to auto-detect this?
SOLARMAX_IP = "192.168.178.155"


if __name__ == "__main__":
    smax = smaxsmt.SolarmaxSmt(host=SOLARMAX_IP)
    print(smax.current_power)
    sys.exit(0)
    # sorting is messed up, do something smater
    for name in dir(smax):
        if name.startswith("_"):
            continue
        attr = inspect.getattr_static(smax, name)
        if isinstance(attr, property):
            print(getattr(smax, name))
